<a href="https://colab.research.google.com/github/adeviney/Advent-of-Code/blob/main/Day11_DumboOctopus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 11: Dumbo Octopus

In [ ]:
import numpy as np

In [ ]:
from scipy.signal import convolve2d
# tried to use this to find neighboring octopi; too confusing
# plan to try to implement this later

In [ ]:
test_input = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

In [ ]:
def step(grid):
  flashed = np.zeros(grid.shape, dtype = 'bool')
  grid = grid + 1

  while (np.any(grid > 9)):
    flash_oct_loc = np.where(grid > 9)
    flashed[flash_oct_loc] = 1

    for x, y in zip(flash_oct_loc[0], flash_oct_loc[1]):
      min_x = x-1 if (x-1)>=0 else 0
      max_x = x+2 if (x+2)< grid.shape[0] else grid.shape[0]-1

      min_y = y-1 if (y-1)>= 0 else 0
      max_y = y+2 if (y+2)< grid.shape[1] else grid.shape[1]-1

      grid[min_x:max_x, min_y:max_y] = 


In [ ]:
np.any(grid > 9)

True

In [ ]:
grid = np.array([list(i) for i in test_input.split('\n')]).astype(int)

In [ ]:
grid = grid+1

In [ ]:
grid.shape

(10, 10)

In [ ]:
grid[9,0]

7

In [ ]:
flash_oct_loc = np.where(grid > 9)

In [ ]:
flash_oct_loc

(array([0, 1, 4, 4, 6, 7, 7, 7, 7, 8, 8, 8, 9]),
 array([2, 4, 5, 9, 4, 1, 2, 4, 5, 1, 4, 6, 2]))

In [ ]:
for x, y in zip(flash_oct_loc[0], flash_oct_loc[1]):
      min_x = x-1 if (x-1)>=0 else 0
      max_x = x+2 if (x+2)< grid.shape[0] else grid.shape[0]-1

      min_y = y-1 if (y-1)>= 0 else 0
      max_y = y+2 if (y+2)< grid.shape[1] else grid.shape[1]-1

      #grid[min_x:max_x, min_y:max_y] = 

In [ ]:
x = 0
y = 2

In [ ]:
x-1

-1

In [ ]:
grid[x-1:x+2, y-1:y+2]

array([], shape=(0, 3), dtype=int64)

In [ ]:
x = 1
y = 2

In [ ]:
mask = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])

res = convolve2d(grid, mask, 'same')

In [ ]:
grid

array([[ 7,  6, 10,  5,  3,  6,  5,  4,  4,  5],
       [ 4,  9,  6,  7, 10,  7,  6,  9,  3,  3],
       [ 7,  4,  8,  6,  7,  7,  8,  3,  9,  5],
       [ 8,  3,  6,  3,  5,  5,  8,  3,  6,  8],
       [ 8,  5,  7,  9,  5, 10,  7,  6,  9, 10],
       [ 6,  3,  8,  9,  7,  4,  6,  8,  6,  7],
       [ 4,  3,  9,  8, 10,  6,  3,  9,  4,  3],
       [ 8, 10, 10,  4, 10, 10,  3,  3,  5,  6],
       [ 6, 10,  6,  8, 10,  6, 10,  7,  7,  6],
       [ 7,  4, 10,  5,  9,  7,  3,  7,  4,  8]])

In [ ]:
res

array([[19, 36, 33, 36, 35, 31, 32, 27, 24, 10],
       [33, 52, 55, 55, 48, 52, 49, 42, 42, 26],
       [28, 51, 44, 52, 50, 56, 48, 52, 40, 29],
       [27, 53, 45, 53, 52, 57, 49, 56, 53, 39],
       [25, 49, 46, 50, 52, 47, 50, 53, 54, 36],
       [23, 50, 53, 63, 61, 54, 53, 50, 56, 32],
       [30, 58, 55, 67, 58, 53, 49, 38, 47, 28],
       [33, 56, 58, 71, 62, 58, 54, 48, 45, 25],
       [39, 61, 61, 64, 59, 62, 46, 42, 46, 30],
       [20, 39, 33, 43, 36, 38, 37, 31, 35, 17]])

In [ ]:
filter = np.array([[1,1,1],[1,0,1],[1,1,1]], dtype = bool)
filter

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [ ]:
for j, x in enumerate(test_input.split('\n')):
  for i, y in enumerate(list(x)):
    print(f"{y} - {i},{j}")

5 - 0,0
4 - 1,0
8 - 2,0
3 - 3,0
1 - 4,0
4 - 5,0
3 - 6,0
2 - 7,0
2 - 8,0
3 - 9,0
2 - 0,1
7 - 1,1
4 - 2,1
5 - 3,1
8 - 4,1
5 - 5,1
4 - 6,1
7 - 7,1
1 - 8,1
1 - 9,1
5 - 0,2
2 - 1,2
6 - 2,2
4 - 3,2
5 - 4,2
5 - 5,2
6 - 6,2
1 - 7,2
7 - 8,2
3 - 9,2
6 - 0,3
1 - 1,3
4 - 2,3
1 - 3,3
3 - 4,3
3 - 5,3
6 - 6,3
1 - 7,3
4 - 8,3
6 - 9,3
6 - 0,4
3 - 1,4
5 - 2,4
7 - 3,4
3 - 4,4
8 - 5,4
5 - 6,4
4 - 7,4
7 - 8,4
8 - 9,4
4 - 0,5
1 - 1,5
6 - 2,5
7 - 3,5
5 - 4,5
2 - 5,5
4 - 6,5
6 - 7,5
4 - 8,5
5 - 9,5
2 - 0,6
1 - 1,6
7 - 2,6
6 - 3,6
8 - 4,6
4 - 5,6
1 - 6,6
7 - 7,6
2 - 8,6
1 - 9,6
6 - 0,7
8 - 1,7
8 - 2,7
2 - 3,7
8 - 4,7
8 - 5,7
1 - 6,7
1 - 7,7
3 - 8,7
4 - 9,7
4 - 0,8
8 - 1,8
4 - 2,8
6 - 3,8
8 - 4,8
4 - 5,8
8 - 6,8
5 - 7,8
5 - 8,8
4 - 9,8
5 - 0,9
2 - 1,9
8 - 2,9
3 - 3,9
7 - 4,9
5 - 5,9
1 - 6,9
5 - 7,9
2 - 8,9
6 - 9,9
