<a href="https://colab.research.google.com/github/adeviney/Advent-of-Code/blob/main/Day11_DumboOctopus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 11: Dumbo Octopus

In [1]:
import numpy as np

In [2]:
from scipy.signal import convolve2d
# tried to use this to find neighboring octopi, failed -- too confusing
# plan to try to implement this later

In [3]:
test_input = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

You can model the energy levels and flashes of light in steps. During a single step, the following occurs:

* First, the energy level of each octopus increases by 1.
* Then, any octopus with an energy level greater than 9 flashes. 
* This increases the energy level of all adjacent octopuses by 1, including octopuses that are diagonally adjacent. If this causes an octopus to have an energy level greater than 9, it also flashes. This process continues as long as new octopuses keep having their energy level increased beyond 9. (An octopus can only flash at most once per step.)
* Finally, any octopus that flashed during this step has its energy level set to 0, as it used all of its energy to flash.

In [4]:
def step(grid):
    # first the energy level of each octopus increases by 1
    grid = grid + 1

    #any octopus with an energy level greater than 9 flashes
    flashed = np.zeros(grid.shape, dtype = 'bool') 
    flash_oct_loc = np.argwhere(np.array(grid) > 9).tolist()
    loc_for_flashed = np.where(grid > 9)
    flashed[loc_for_flashed] = 1

    
    # this loop increases the energy level of all adjacent octopi
    while (len(flash_oct_loc) != 0):
        coord = flash_oct_loc.pop()
        x = coord[0]
        y = coord[1]
        min_x = x-1 if (x-1)>=0 else 0
        max_x = x+2 if (x+2)< grid.shape[0] else grid.shape[0]

        min_y = y-1 if (y-1)>= 0 else 0
        max_y = y+2 if (y+2)< grid.shape[1] else grid.shape[1]

        for grid_x in range(min_x, max_x):
            for grid_y in range(min_y, max_y):
                # only if the adjacent octopi has not already flashed is the 
                # energy of this octopi increased
                if flashed[grid_x, grid_y] == 0:
                    grid[grid_x, grid_y] += 1
                    # if the increase happens to put the energy above 9, this
                    # octopi also flashes and is appended to the stack of 
                    # octopi for which we must increase the energy of its 
                    # neighbors
                    if grid[grid_x, grid_y] > 9:
                        flash_oct_loc.append([grid_x, grid_y])
                        flashed[grid_x, grid_y] = 1

         # any octopus that flashd during this step is reset to 0 energy               
        grid = np.where(grid == 10, 0, grid)
    return [flashed.sum(), grid]
                        

## Part 1

### Test data

In [5]:
tdata = np.array([list(i) for i in test_input.split('\n')]).astype(int)

In [6]:
grid = tdata
grid

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [7]:
c = 0
for i in range(100):
    [num_flashes, grid] = step(grid)
    c+=num_flashes
print(c)

1656


### Real data

In [8]:
with open('day11input.txt') as f:
    data = np.array([list(i) for i in f.read().strip().split('\n')]).astype(int)
data

array([[1, 3, 2, 6, 2, 5, 3, 3, 1, 5],
       [3, 4, 2, 7, 7, 2, 8, 1, 1, 3],
       [5, 7, 5, 1, 6, 1, 2, 5, 4, 2],
       [6, 5, 4, 3, 8, 6, 8, 3, 2, 2],
       [4, 4, 2, 2, 5, 2, 6, 2, 2, 1],
       [2, 2, 3, 4, 3, 2, 5, 6, 4, 7],
       [1, 7, 7, 3, 1, 7, 4, 8, 8, 7],
       [7, 2, 8, 1, 3, 2, 1, 6, 7, 4],
       [6, 5, 6, 2, 5, 1, 3, 1, 1, 8],
       [4, 8, 2, 4, 5, 4, 1, 5, 2, 2]])

In [9]:
grid = data

In [10]:
c = 0
for i in range(100):
    [num_flashes, grid] = step(grid)
    c += num_flashes
print(c)

1749


## Part 2

### test data

In [11]:
grid = tdata

In [12]:
c = 0
while (num_flashes != grid.size):
    [num_flashes, grid] = step(grid)
    c+=1
print(c)

195


### real data

In [13]:
grid = data
grid

array([[1, 3, 2, 6, 2, 5, 3, 3, 1, 5],
       [3, 4, 2, 7, 7, 2, 8, 1, 1, 3],
       [5, 7, 5, 1, 6, 1, 2, 5, 4, 2],
       [6, 5, 4, 3, 8, 6, 8, 3, 2, 2],
       [4, 4, 2, 2, 5, 2, 6, 2, 2, 1],
       [2, 2, 3, 4, 3, 2, 5, 6, 4, 7],
       [1, 7, 7, 3, 1, 7, 4, 8, 8, 7],
       [7, 2, 8, 1, 3, 2, 1, 6, 7, 4],
       [6, 5, 6, 2, 5, 1, 3, 1, 1, 8],
       [4, 8, 2, 4, 5, 4, 1, 5, 2, 2]])

In [14]:
c = 0
num_flashes = 0
while (num_flashes != grid.size):
    [num_flashes, grid] = step(grid)
    c+=1
print(c)

285
